update paper based on feedback from #39
IMMM-SFA/mosartwmpy pull request #40
Opened 2021-05-27 19:59 UTC by thurber

2021-05-28 21:34 UTC, crvernon requested changes
Well done @thurber !  Only a few formatting issues that need to be addressed.

I compiled this using the JOSS preview service and found a few citation formatting issues.  See the attached...
[m4eusqfzjw6pxl8kzlih.pdf](https://github.com/IMMM-SFA/mosartwmpy/files/6563401/m4eusqfzjw6pxl8kzlih.pdf)

2021-05-28 21:34 UTC, crvernon commented on paper/paper.md
> +In addition to `mosartwmpy`'s ancestor MOSART-WM, several other models are commonly used in hydrologic modeling, each excelling at different processes. The Community Land Model (CLM) [@https://doi.or
You want these to be in the same parenthesis:  `(CLM) [@https://doi.org/10.1029/2018MS001583]`

So you need to format like:  `[CLM; @https://doi.org/10.1029/2018MS001583]`

which should give you `(CLM; Lawrence et al, 2019)` once compiled

2021-05-28 21:34 UTC, crvernon commented on paper/paper.bib
> +  author = { Colorado's Decision Support Systems (CDSS)},
you will likely have to change author to:  `{CDSS},` because this will output like:  `((CDSS), 2018) once compiled`

2021-05-28 21:34 UTC, crvernon commented on paper/paper.bib
> +@misc{glofrim,
Change this ref to the following to ensure we have correct last, first formatting:

```
@article{hoch2017glofrim,
  title={GLOFRIM v1. 0--A globally applicable computational framework for integrated hydrological--hydrodynamic modelling},
  author={Hoch, Jannis M and Neal, Jeffrey C and Baart, Fedor and Beek, Rens van and Winsemius, Hessel C and Bates, Paul D and Bierkens, Marc FP},
  journal={Geoscientific Model Development},
  volume={10},
  number={10},
  pages={3913--3929},
  year={2017},
  publisher={Copernicus GmbH}
}
```

2021-05-28 22:13 UTC, thurber commented on paper/paper.md
> +In addition to `mosartwmpy`'s ancestor MOSART-WM, several other models are commonly used in hydrologic modeling, each excelling at different processes. The Community Land Model (CLM) [@https://doi.or
Good catch, updated!

2021-05-28 22:14 UTC, thurber commented on paper/paper.bib
> +  author = { Colorado's Decision Support Systems (CDSS)},
updated

2021-05-28 22:14 UTC, thurber commented on paper/paper.bib
> +@misc{glofrim,
whoops, thanks! updated

2021-05-28 23:17 UTC, crvernon approved these changes
Looks good after compile now.  Good to merge from my end.

2021-05-28 23:24 UTC, crvernon commented
I think your numpy wheel may be giving you a fuss on the Windows GitHub action.

Also, I would yank out the codecov push on all except the linux or mac builds.  Only need this communicating with codecov on one OS. 

So the block that runs codecov goes to this for all but one OS:

```yaml
        - name: Run tests     
           run: |           
                   pip install pytest
                   pytest
```

2021-06-01 15:22 UTC, thurber commented
@crvernon, I disabled the windows workflow for now -- will try to come up with a more sustainable solution as I work some of the other issues.

2021-06-01 15:25 UTC, merged