64 bil to parquet
IMMM-SFA/mosartwmpy pull request #67
Opened 2021-11-16 23:21 UTC by erexer

2021-11-17 00:16 UTC, thurber requested changes
Nice work picking up all these new concepts and creating this script in such a small amount of time! Left my feedback below, let me know if you want to talk through any of them!

2021-11-17 00:16 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +                     "crs": pycrs.parse.from_epsg_code(epsg_code).to_proj4()})
i think you might be able to just use `bil.crs` here instead of parsing

2021-11-17 00:16 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +    pq.write_table(table, parquet_elevation_path)
pandas dataframes have an `to_parquet` method that might be somewhat preferable to the long form here

2021-11-17 00:16 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +    with rasterio.open(cropped_output_path, "w", **out_meta) as dest:
is it possible to skip writing the cropped file to disk? i.e. to work with it in memory?

2021-11-17 00:16 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +def getFeatures(gdf):
could be cleaner to just perform this inline where needed, with the `json` import at the top as usual

2021-11-17 00:16 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +bil_to_parquet()
also have a look at the `entry_points` entry in the `setup.py` for how to add this script as command line utility included with the package

2021-11-17 00:16 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +        upscale_elevation=False,
this one isn't used~

2021-11-17 00:16 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +    default='../../input/elevation/na_dem_30s_bil/na_dem_30s.bil',
i think we'll need a way to read the Central America file as well, and overlay with the missing sections from the North America file

2021-11-18 01:52 UTC, erexer commented on mosartwmpy/utilities/bil_to_parquet.py
> +    default='../../input/elevation/na_dem_30s_bil/na_dem_30s.bil',
That seems like a different enough task that I'm in favor of creating a new utility. But I'm also not super familiar with the workflow yet, thoughts?

2021-11-18 15:46 UTC, thurber commented on mosartwmpy/utilities/bil_to_parquet.py
> +    default='../../input/elevation/na_dem_30s_bil/na_dem_30s.bil',
i think since the typical domain isn't fully covered by the NA file, it will be necessary to support combinations; but we can have a new task for that aspect

2021-11-18 15:50 UTC, thurber approved these changes

2021-11-18 20:30 UTC, merged