initial abm toggle
IMMM-SFA/mosartwmpy pull request #74
Opened 2022-01-19 00:23 UTC by erexer

add option to config to enable using ABM to calculate water management demand, add ABM code

2022-01-19 16:47 UTC, thurber requested changes

2022-01-19 16:47 UTC, thurber commented on mosartwmpy/config_defaults.yaml
> +        abm: false
i'm a fan of spelling things out as much as possible in code and configuration, and we'll also need to be adding more options to this abm over time (for instance references to the parameter/calibration files), so i recommend a structure more like:

```yaml
    demand:
        farmer_agent_based_model:
            enabled: false
```

2022-01-19 16:47 UTC, thurber commented on mosartwmpy/input/demand.py
> +from mosartwmpy.abm import abm as ABM
Let's give this ABM a more specific name, since theoretically other ABMs could be developed in the future... maybe FarmerAgent or something?

2022-01-19 16:47 UTC, thurber commented on mosartwmpy/input/demand.py
> +        ABM.calc_demand(config, str(current_time.year), "1", './legacy_reservoir_file.nc')
i believe this will cause the optimization to run every time wmpy requests demand -- the FarmerAgent may need a way to check if it has already produced the necessary files and skip processing if so.

2022-01-19 16:47 UTC, thurber commented on mosartwmpy/input/demand.py
> +        path = config.get('simulation.output_path') + '/demand/demand_' + current_time.strftime('%Y') + '_' + current_time.strftime('%m') + '.nc'
for the demand output naming convention, i recommend following the pattern of the general wmpy output, which is to name the files using the Model instance's `name` property. This will help folks keep their data organized if running many simulations.

2022-01-19 16:47 UTC, thurber commented on mosartwmpy/abm/abm.py
> +from benedict.dicts import benedict as Benedict
this file still needs a lot of help, but i know that's on your radar so i'm not really going to review it at the moment!

2022-01-19 16:50 UTC, thurber commented
will eventually need to roll in the new dependencies into `setup.py`, but can leave that til we've trimmed them down a bit

2022-01-24 21:43 UTC, erexer commented on mosartwmpy/input/demand.py
> +        ABM.calc_demand(config, str(current_time.year), "1", './legacy_reservoir_file.nc')
I'm checking the existence in the actual abm code but open to changing that.

2022-09-15 19:31 UTC, thurber requested changes

2022-09-15 19:31 UTC, thurber commented on mosartwmpy/config_defaults.yaml
> +        # farmer Agent Based Model (ABM) calculation of demand
Can you add some short commends to each entry describing it? in particular, mu and warmup_period need explanation

2022-09-15 19:31 UTC, thurber commented on mosartwmpy/tests/test_config.yaml
>  simulation:
What ended up being the resolution here?

2022-09-19 19:51 UTC, erexer commented on mosartwmpy/tests/test_config.yaml
>  simulation:
switching from `pkgutil` to `pkg_resources` fixed the yaml import error, not sure why though.

2022-09-19 21:16 UTC, merged